# SPDX-FileCopyrightText: Copyright (c) 2019-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v6.0.0'
    hooks:
      - id: end-of-file-fixer
        exclude: ^(datasets|helmchart)/.*\.(mps|json|yaml|yml|txt)$
      - id: trailing-whitespace
        exclude: ^datasets/.*\.(mps|json|yaml|yml|txt)$
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
        files: \.(yaml)$
        exclude: ^(helmchart)/.*\.(yaml)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
        args: [--fix, --config, pyproject.toml]
      - id: ruff-format
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        # https://github.com/PyCQA/pydocstyle/issues/603
        additional_dependencies: [toml]
        args: ["--config=pyproject.toml"]
        exclude: |
          (?x)^(
            ci|
            cpp|
            conda|
            docs|
            notebooks
          )
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.4
    hooks:
      - id: clang-format
        files: \.(cu|cuh|h|hpp|cpp|inl)$
        types_or: [file]
        args: ['-fallback-style=none', '-style=file', '-i']
  - repo: https://github.com/rapidsai/dependency-file-generator
    rev: v1.20.0
    hooks:
      - id: rapids-dependency-file-generator
        args: ["--clean", "--warn-all", "--strict"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v1.3.3
    hooks:
      - id: verify-copyright
        args: [--fix, --spdx]
        files: |
          (?x)
            [.](cmake|c|cpp|cu|cuh|h|hpp|sh|pxd|py|pyx|pdx|hpp[.]in|bat)$|
            CMakeLists[.]txt$|
            recipe[.]yaml$|
            ^[.]github/workflows/|
            ^[.]coderabbit[.]yaml$|
            ^[.]pre-commit-config[.]yaml$|
            Dockerfile$|
            dependencies[.]yaml$|
            Makefile$|
            setup[.]cfg$|
            pyproject[.]toml$
        exclude: |
          (?x)^(
            ^cpp/tests/utilities/cxxopts.hpp
          )
      - id: verify-pyproject-license
        # ignore the top-level pyproject.toml, which doesn't
        # have or need a [project] table
        exclude: |
          (?x)
            ^pyproject[.]toml$
  - repo: local
    hooks:
      - id: update-versions
        name: Update versions1.json
        entry: python ci/utils/update_doc_versions.py
        language: system
        files: docs/cuopt/source/versions1.json


default_language_version:
      python: python3
