# SPDX-FileCopyrightText: Copyright (c) 2021-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: |
          branch: git branch the workflow run targets.
          Required even when 'sha' is provided because it is also used for organizing artifacts.
        required: true
        type: string
      date:
        description: "date: Date (YYYY-MM-DD) this run is for. Used to organize artifacts produced by nightly builds"
        required: true
        type: string
      sha:
        description: "sha: full git commit SHA to check out"
        required: true
        type: string
      build_type:
        description: "build_type: one of [branch, nightly, pull-request]"
        type: string
        default: nightly

jobs:
  conda-cpp-tests:
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-tests.yaml@release/26.02
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      script: ci/test_cpp.sh
    secrets:
      script-env-secret-1-key: CUOPT_DATASET_S3_URI
      script-env-secret-1-value: ${{ secrets.CUOPT_DATASET_S3_URI }}
      script-env-secret-2-key: CUOPT_AWS_ACCESS_KEY_ID
      script-env-secret-2-value: ${{ secrets.CUOPT_AWS_ACCESS_KEY_ID }}
      script-env-secret-3-key: CUOPT_AWS_SECRET_ACCESS_KEY
      script-env-secret-3-value: ${{ secrets.CUOPT_AWS_SECRET_ACCESS_KEY }}
  conda-python-tests:
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@release/26.02
    with:
      run_codecov: false
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      script: ci/test_python.sh
    secrets:
      script-env-secret-1-key: CUOPT_DATASET_S3_URI
      script-env-secret-1-value: ${{ secrets.CUOPT_DATASET_S3_URI }}
      script-env-secret-2-key: CUOPT_AWS_ACCESS_KEY_ID
      script-env-secret-2-value: ${{ secrets.CUOPT_AWS_ACCESS_KEY_ID }}
      script-env-secret-3-key: CUOPT_AWS_SECRET_ACCESS_KEY
      script-env-secret-3-value: ${{ secrets.CUOPT_AWS_SECRET_ACCESS_KEY }}
  wheel-tests-cuopt:
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@release/26.02
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      script: ci/test_wheel_cuopt.sh
    secrets:
      script-env-secret-1-key: CUOPT_DATASET_S3_URI
      script-env-secret-1-value: ${{ secrets.CUOPT_DATASET_S3_URI }}
      script-env-secret-2-key: CUOPT_AWS_ACCESS_KEY_ID
      script-env-secret-2-value: ${{ secrets.CUOPT_AWS_ACCESS_KEY_ID }}
      script-env-secret-3-key: CUOPT_AWS_SECRET_ACCESS_KEY
      script-env-secret-3-value: ${{ secrets.CUOPT_AWS_SECRET_ACCESS_KEY }}
  wheel-tests-cuopt-server:
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@release/26.02
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      script: ci/test_wheel_cuopt_server.sh
    secrets:
      script-env-secret-1-key: CUOPT_DATASET_S3_URI
      script-env-secret-1-value: ${{ secrets.CUOPT_DATASET_S3_URI }}
      script-env-secret-2-key: CUOPT_AWS_ACCESS_KEY_ID
      script-env-secret-2-value: ${{ secrets.CUOPT_AWS_ACCESS_KEY_ID }}
      script-env-secret-3-key: CUOPT_AWS_SECRET_ACCESS_KEY
      script-env-secret-3-value: ${{ secrets.CUOPT_AWS_SECRET_ACCESS_KEY }}
  conda-notebook-tests:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@release/26.02
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      node_type: "gpu-l4-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:26.02-latest"
      script: ci/test_notebooks.sh
